name: CI

on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        env:
          SUPER_SECRET_TOKEN: ${{ secrets.SUPER_SECRET_TOKEN }}
